import json

# Ruta al archivo JSON en tu sistema local
file_path = 'CertificadoBalance.json'

# Cargando el contenido del archivo JSON en una variable
with open(file_path, 'r') as file:
    data = json.load(file)

# Guardando el contenido en el mismo archivo con indentación (si es necesario)
with open(file_path, 'w') as file:
    json.dump(data, file, indent=4)

#SampleCals

file_path = "SampleCalsOriginal.json"

# Carga los datos JSON
with open(file_path, "r") as file:
    data = json.load(file)

# (El código para modificar los datos va aquí)

# Mapeo completo de nombres de grupos
group_name_mapping = {
    'Humedad - 160 °C @ 8 min': 'Moisture - 160°C @ 8 min',
    'Moisture - 160°C /8 min - Not Accredited': 'Moisture - 160°C @ 8 min - Not Accredited',
    'Moisture - 5 grams @ 8m @ 160 deg c': 'Moisture - 5 grams @ 8 min @ 160°C',
    'Peso': 'Weight',
    'Peso - Ascendente': 'Weight - Ascending',
    'Peso - Centro Excentricidad': 'Weight - Eccentricity Center',
    'Peso - Centro de Excentricidad': 'Weight - Eccentricity Center',
    'Peso - Centro de excentricidad': 'Weight - Eccentricity Center',
    'Peso - Descendente': 'Weight - Descending',
    'Peso - Desviacion Estandar': 'Weight - Std Dev',
    'Peso - Desviación Estándar': 'Weight - Std Dev',
    'Peso - Eccentricidad Centro': 'Weight - Eccentricity Center',
    'Peso - Eccentricidad Noreste': 'Weight - Eccentricity Northeast',
    'Peso - Eccentricidad Noroeste': 'Weight - Eccentricity Northwest',
    'Peso - Eccentricidad Sureste': 'Weight - Eccentricity Southeast',
    'Peso - Eccentricidad Suroeste': 'Weight - Eccentricity Southwest',
    'Peso - Escentrecidad Centro': 'Weight - Eccentricity Center',
    'Peso - Escentrecidad Este': 'Weight - Eccentricity East',
    'Peso - Escentrecidad Norte': 'Weight - Eccentricity North',
    'Peso - Escentrecidad Oeste': 'Weight - Eccentricity West',
    'Peso - Escentrecidad Sur': 'Weight - Eccentricity South',
    'Peso - Excentricidad': 'Weight - Eccentricity',
    'Peso - Excentricidad Centro': 'Weight - Eccentricity Center',
    'Peso - Excentricidad Noroeste': 'Weight - Eccentricity Northwest',
    'Peso - Excentricidad Central': 'Weight - Eccentricity Center',
    'Peso - Excentricidad Centro': 'Weight - Eccentricity Center',
    'Peso - Excentricidad Este': 'Weight - Eccentricity East',
    'Peso - Excentricidad NorEste': 'Weight - Eccentricity Northeast',
    'Peso - Excentricidad NorOeste': 'Weight - Eccentricity Northwest',
    'Peso - Excentricidad Nordeste': 'Weight - Eccentricity Northeast',
    'Peso - Excentricidad Noreste': 'Weight - Eccentricity Northeast',
    'Peso - Excentricidad Noroeste': 'Weight - Eccentricity Northwest',
    'Peso - Excentricidad Norte': 'Weight - Eccentricity North',
    'Peso - Excentricidad Norteste': 'Weight - Eccentricity Northeast',
    'Peso - Excentricidad Oeste': 'Weight - Eccentricity West',
    'Peso - Excentricidad Soroeste': 'Weight - Eccentricity Southwest',
    'Peso - Excentricidad Sudeste': 'Weight - Eccentricity Southeast',
    'Peso - Excentricidad Suoeste': 'Weight - Eccentricity Southwest',
    'Peso - Excentricidad Sur': 'Weight - Eccentricity South',
    'Peso - Excentricidad SurEste': 'Weight - Eccentricity Southeast',
    'Peso - Excentricidad SurOeste': 'Weight - Eccentricity Southwest',
    'Peso - Excentricidad Sureste': 'Weight - Eccentricity Southeast',
    'Peso - Excentricidad Suroeste': 'Weight - Eccentricity Southwest',
    'Peso - Excentricidad del Centro': 'Weight - Eccentricity Center',
    'Peso - Excentricidad del Este': 'Weight - Eccentricity East',
    'Peso - Excentricidad del Noroeste': 'Weight - Eccentricity Northwest',
    'Peso - Excentricidad del Norte': 'Weight - Eccentricity North',
    'Peso - Excentricidad del Norte-Este': 'Weight - Eccentricity Northeast',
    'Peso - Excentricidad del Norte-Oeste': 'Weight - Eccentricity Northwest',
    'Peso - Excentricidad del Oeste': 'Weight - Eccentricity West',
    'Peso - Excentricidad del Sur': 'Weight - Eccentricity South',
    'Peso - Excentricidad del Sur-Este': 'Weight - Eccentricity Southeast',
    'Peso - Excentricidad del Sur-Oeste': 'Weight - Eccentricity Southwest',
    'Peso - Excentricidad del sudeste': 'Weight - Eccentricity Southeast',
    'Peso - Excentricidad noreste': 'Weight - Eccentricity Northeast',
    'Peso - Excentricidad sureste': 'Weight - Eccentricity Southeast',
    'Peso - Excentricidad suroeste': 'Weight - Eccentricity Southwest',
    'Peso - Excentricity Noreste': 'Weight - Eccentricity Northeast',
    'Peso - Lineaalidad Descendente': 'Weight - Linearity Descending',
    'Peso - Linealidad Ascendente': 'Weight - Linearity Ascending',
    'Peso - Linealidad Decendente': 'Weight - Linearity Descending',
    'Peso - Linealidad Descendente': 'Weight - Linearity Descending',
    'Peso - Linealidad Desscendente': 'Weight - Linearity Descending',
    'Peso - Linealidad Dn': 'Weight - Linearity Down',
    'Peso - Linealidad Up': 'Weight - Linearity Up',
    'Peso - Repeatability Value': 'Weight - Repeatability',
    'Peso - Sensitividad': 'Weight - Sensitivity',
    'Surface Density - AREA=144 CM2@1.0 G': 'Surface Density - Area=144 cm² @ 1.0 g',
    'Surface Density - AREA=225CM2@1.3458 G': 'Surface Density - Area=225 cm² @ 1.3458 g',
    'Surface Density - AREA=25 CM2@0.45 G': 'Surface Density - Area=25 cm² @ 0.45 g',
    'Surface Density - AREA=97.8117 CM2@0.894 G': 'Surface Density - Area=97.8117 cm² @ 0.894 g',
    'Surface Density - AREA=98.8 CM2 @0.8972 G': 'Surface Density - Area=98.8 cm² @ 0.8972 g',
    'Temperatura - Medición': 'Temperature - Measurement',
    'Temperature - Measure': 'Temperature - Measurement',
    'Weight': 'Weight',
    'Weight - 0.05 g - Std Dev': 'Weight - 0.05 g - Std Dev',
    'Weight - 0.1 g - Std Dev': 'Weight - 0.1 g - Std Dev',
    'Weight - 0.2 g - Std Dev': 'Weight - 0.2 g - Std Dev',
    'Weight - 10 g - Std Dev': 'Weight - 10 g - Std Dev',
    'Weight - 100 g - Std Dev': 'Weight - 100 g - Std Dev',
    'Weight - 100 g Ascending Repeatability': 'Weight - 100 g Ascending Repeatability',
    'Weight - 100 g Descending Repeatability': 'Weight - 100 g Descending Repeatability',
    'Weight - 1000 g - Std Dev': 'Weight - 1000 g - Std Dev',
    'Weight - 1000 g Ascending Repeatability': 'Weight - 1000 g Ascending Repeatability',
    'Weight - 1000 g Descending Repeatability': 'Weight - 1000 g Descending Repeatability',
    'Weight - 20 g - Std Dev': 'Weight - 20 g - Std Dev',
    'Weight - 200 g - Std Dev': 'Weight - 200 g - Std Dev',
    'Weight - 200 g Ascending Repeatability': 'Weight - 200 g Ascending Repeatability',
    'Weight - 200 g Descending Repeatability': 'Weight - 200 g Descending Repeatability',
    'Weight - 500 g - Std Dev': 'Weight - 500 g - Std Dev',
    'Weight - 500 g Ascending Repeatability': 'Weight - 500 g Ascending Repeatability',
    'Weight - 500 g Descending Repeatability': 'Weight - 500 g Descending Repeatability',
    'Weight - Ascendent Linearity': 'Weight - Ascending Linearity',
    'Weight - Ascending Linearity': 'Weight - Ascending Linearity',
    'Weight - Eccentricit North': 'Weight - Eccentricity North',
    'Weight - Eccentricit South': 'Weight - Eccentricity South',
    'Weight - Eccentricity': 'Weight - Eccentricity',
    'Weight - Eccentricity - Southeast': 'Weight - Eccentricity Southeast',
    'Weight - Eccentricity SouthEast': 'Weight - Eccentricity Southeast',
    'Weight - Eccentricity - Center': 'Weight - Eccentricity Center',
    'Weight - Eccentricity - NorthEast': 'Weight - Eccentricity Northeast',
    'Weight - Eccentricity - Northeast': 'Weight - Eccentricity Northeast',
    'Weight - Eccentricity - Northwest': 'Weight - Eccentricity Northwest',
    'Weight - Eccentricity - SouthEast': 'Weight - Eccentricity Southeast',
    'Weight - Eccentricity - SouthWest': 'Weight - Eccentricity Southwest',
    'Weight - Eccentricity - Southeast': 'Weight - Eccentricity Southeast',
    'Weight - Eccentricity - Southwest': 'Weight - Eccentricity Southwest',
    'Weight - Eccentricity - Std Dev': 'Weight - Eccentricity - Std Dev',
    'Weight - Eccentricity Center': 'Weight - Eccentricity Center',
    'Weight - Eccentricity East': 'Weight - Eccentricity East',
    'Weight - Eccentricity North': 'Weight - Eccentricity North',
    'Weight - Eccentricity North-East': 'Weight - Eccentricity Northeast',
    'Weight - Eccentricity North-West': 'Weight - Eccentricity Northwest',
    'Weight - Eccentricity NorthEast': 'Weight - Eccentricity Northeast',
    'Weight - Eccentricity NorthWest': 'Weight - Eccentricity Northwest',
    'Weight - Eccentricity Northeast': 'Weight - Eccentricity Northeast',
    'Weight - Eccentricity Northwest': 'Weight - Eccentricity Northwest',
    'Weight - Eccentricity Noth': 'Weight - Eccentricity North',
    'Weight - Eccentricity Sourtheast': 'Weight - Eccentricity Southeast',
    'Weight - Eccentricity Sourthwest': 'Weight - Eccentricity Southwest',
    'Weight - Eccentricity South': 'Weight - Eccentricity South',
    'Weight - Eccentricity South-East': 'Weight - Eccentricity Southeast',
    'Weight - Eccentricity South-West': 'Weight - Eccentricity Southwest',
    'Weight - Eccentricity SouthEast': 'Weight - Eccentricity Southeast',
    'Weight - Eccentricity SouthWest': 'Weight - Eccentricity Southwest',
    'Weight - Eccentricity Southeast': 'Weight - Eccentricity Southeast',
    'Weight - Eccentricity Southwest': 'Weight - Eccentricity Southwest',
    'Weight - Eccentricity West': 'Weight - Eccentricity West',
    'Weight - EccentricitySouthwest': 'Weight - Eccentricity Southwest',
    'Weight - Excenticity Center': 'Weight - Eccentricity Center',
    'Weight - Excentricity': 'Weight - Eccentricity',
    'Weight - Excentricity Northwest': 'Weight - Eccentricity Northwest',
    'Weight - Excentricity souhteast': 'Weight - Eccentricity Southeast',
    'Weight - Excentricity - Center': 'Weight - Eccentricity Center',
    'Weight - Excentricity - East': 'Weight - Eccentricity East',
    'Weight - Excentricity - North': 'Weight - Eccentricity North',
    'Weight - Excentricity - South': 'Weight - Eccentricity South',
    'Weight - Excentricity - West': 'Weight - Eccentricity West',
    'Weight - Excentricity Center': 'Weight - Eccentricity Center',
    'Weight - Excentricity East': 'Weight - Eccentricity East',
    'Weight - Excentricity Nort': 'Weight - Eccentricity North',
    'Weight - Excentricity Nort west': 'Weight - Eccentricity Northwest',
    'Weight - Excentricity Norteast': 'Weight - Eccentricity Northeast',
    'Weight - Excentricity North': 'Weight - Eccentricity North',
    'Weight - Excentricity North East': 'Weight - Eccentricity Northeast',
    'Weight - Excentricity NorthEast': 'Weight - Eccentricity Northeast',
    'Weight - Excentricity NorthWest': 'Weight - Eccentricity Northwest',
    'Weight - Excentricity Northeast': 'Weight - Eccentricity Northeast',
    'Weight - Excentricity Northest': 'Weight - Eccentricity Northeast',
    'Weight - Excentricity Northwest': 'Weight - Eccentricity Northwest',
    'Weight - Excentricity Nortwest': 'Weight - Eccentricity Northwest',
    'Weight - Excentricity South': 'Weight - Eccentricity South',
    'Weight - Excentricity South East': 'Weight - Eccentricity Southeast',
    'Weight - Excentricity South West': 'Weight - Eccentricity Southwest',
    'Weight - Excentricity SouthEast': 'Weight - Eccentricity Southeast',
    'Weight - Excentricity SouthWest': 'Weight - Eccentricity Southwest',
    'Weight - Excentricity Southeast': 'Weight - Eccentricity Southeast',
    'Weight - Excentricity Southwest': 'Weight - Eccentricity Southwest',
    'Weight - Excentricity Soutwest': 'Weight - Eccentricity Southwest',
    'Weight - Excentricity West': 'Weight - Eccentricity West',
    'Weight - Excentricity southwest': 'Weight - Eccentricity Southwest',
    'Weight - Excenyricity Center': 'Weight - Eccentricity Center',
    'Weight - Lineality Down': 'Weight - Linearity Down',
    'Weight - Lineality Up': 'Weight - Linearity Up',
    'Weight - Linearity': 'Weight - Linearity',
    'Weight - Linearity Up': 'Weight - Linearity Up',
    'Weight - Linearity DW': 'Weight - Linearity Down',
    'Weight - Linearity Dn': 'Weight - Linearity Down',
    'Weight - Linearity Down': 'Weight - Linearity Down',
    'Weight - Linearity Dw': 'Weight - Linearity Down',
    'Weight - Linearity UP': 'Weight - Linearity Up',
    'Weight - Linearity Up': 'Weight - Linearity Up',
    'Weight - Linearity dn': 'Weight - Linearity Down',
    'Weight - Linearity down': 'Weight - Linearity Down',
    'Weight - Linearity up': 'Weight - Linearity Up',
    'Weight - Repeatability': 'Weight - Repeatability',
    'Weight - Repeatability Value': 'Weight - Repeatability',
    'Weight - Sensitivity': 'Weight - Sensitivity',
    'Weight - Std Dev': 'Weight - Std Dev',
    'Weight - StdDev': 'Weight - Std Dev',
    'Weight - g--Excentricity': 'Weight - g - Eccentricity',
    'Weight - g--StdDev': 'Weight - g - Std Dev'
}

# Itera a través de cada registro y actualiza los nombres de los grupos
for item in data:
    for group in item.get("Datasheet", []):
        original_group_name = group["Group"]
        if original_group_name in group_name_mapping:
            group["Group"] = group_name_mapping[original_group_name]

# Guarda los datos modificados en un nuevo archivo JSON
modified_file_path = "SampleCals.json"
with open(modified_file_path, "w") as file:
    json.dump(data, file, indent=4)